# Generated by Django 4.0.6 on 2022-07-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nazev_atributu_id', models.IntegerField(blank=True, null=True)),
                ('hodnota_atributu_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(blank=True, max_length=256)),
                ('kod', models.CharField(blank=True, max_length=256)),
                ('zobrazit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hodnota', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(blank=True, max_length=256)),
                ('obrazek_id', models.IntegerField(blank=True, null=True)),
                ('products_ids', models.CharField(blank=True, max_length=256)),
                ('attributes_ids', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('obrazek', models.CharField(blank=True, max_length=256)),
                ('nazev', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(blank=True, max_length=512)),
                ('cena', models.CharField(blank=True, max_length=32)),
                ('mena', models.CharField(blank=True, max_length=8)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('attribute', models.IntegerField()),
                ('product', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product', models.IntegerField()),
                ('obrazek_id', models.IntegerField()),
                ('nazev', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
